"""users access_token for RGPD self-service

Revision ID: e3a07849ada9
Revises: c375ad4fa2bb
Create Date: 2026-08-26 13:55:40.621064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a07849ada9'
down_revision: Union[str, Sequence[str], None] = 'c375ad4fa2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_access_token'), 'users', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_access_token'), table_name='users')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
