"""sessions

Revision ID: 9dd893772cc0
Revises: 86b8fb32827d
Create Date: 2026-08-25 22:22:43.011729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd893772cc0'
down_revision: Union[str, Sequence[str], None] = '86b8fb32827d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('panel', 'workshop', 'competition', 'keynote', 'lightning_talk', 'fireside_chat', 'b2b', 'job_fair', 'networking', 'after_party', name='session_category'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_category'), 'sessions', ['category'], unique=False)
    op.create_index(op.f('ix_sessions_day_id'), 'sessions', ['day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # drop_table alone handles the FK-backed index (MySQL forbids dropping an
    # index that still backs a foreign key before the FK itself is gone).
    op.drop_table('sessions')
