"""speakers, ambassadors, partners, exhibitors

Revision ID: 7b6712058249
Revises: a3f8aaae2d58
Create Date: 2026-08-25 22:35:06.225348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6712058249'
down_revision: Union[str, Sequence[str], None] = 'a3f8aaae2d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_position', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('stand_type', sa.Enum('Standard', 'Premium', 'Mutualisé', name='exhibitor_stand_type'), nullable=False),
    sa.Column('reps_count', sa.Integer(), nullable=False),
    sa.Column('linked_partner_level', sa.String(length=50), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=False),
    sa.Column('equipment_needs', sa.Text(), nullable=True),
    sa.Column('side_activities', sa.Text(), nullable=True),
    sa.Column('visuals_url', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.Enum('Virement bancaire', 'Mobile Money', 'Chèque', "À définir avec l'équipe Synca", name='exhibitor_payment_method'), nullable=True),
    sa.Column('rules_accepted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('gdpr_consent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'contacted', 'negotiating', 'confirmed', 'rejected', name='exhibitor_status'), server_default='pending', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitors_status'), 'exhibitors', ['status'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title_role', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('intervention_format', sa.Enum('Keynote', 'Panel', 'Workshop', 'Lightning Talk', 'Fireside Chat', name='speaker_intervention_format'), nullable=False),
    sa.Column('intervention_title', sa.String(length=100), nullable=False),
    sa.Column('theme', sa.Enum('IA', 'EdTech', 'Entrepreneuriat', 'Carrières', 'Impact', 'Cybersec', name='speaker_theme'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('audience_level', sa.Enum('Débutant', 'Intermédiaire', 'Avancé', 'Tous', name='speaker_audience_level'), nullable=True),
    sa.Column('language', sa.Enum('Français', 'Anglais', 'Bilingue', 'Autre', name='speaker_language'), nullable=True),
    sa.Column('past_experience', sa.Text(), nullable=True),
    sa.Column('video_link', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.Enum('Oui confirmé', 'Sous réserve', 'Besoin aide déplacement', name='speaker_availability'), nullable=True),
    sa.Column('departure_city', sa.String(length=100), nullable=True),
    sa.Column('needs_accommodation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('video_consent', sa.Enum('Oui sans restriction', 'Oui avec validation', 'Non', name='speaker_video_consent'), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='speaker_status'), server_default='pending', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_status'), 'speakers', ['status'], unique=False)
    op.create_table('ambassadors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('current_profile', sa.Enum('Étudiant', 'Professionnel', 'Créateur de contenu', 'Entrepreneur', name='ambassador_current_profile'), nullable=True),
    sa.Column('institution_company', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('social_handles', sa.JSON(), nullable=True),
    sa.Column('followers_range', sa.Enum('<500', '500-2K', '2K-10K', '+10K', name='ambassador_followers_range'), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('mobilization_plan', sa.Text(), nullable=False),
    sa.Column('estimated_reach', sa.Enum('5–10', '10–25', '25–50', '+50', name='ambassador_estimated_reach'), nullable=True),
    sa.Column('previous_synca', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('preferred_channels', sa.Text(), nullable=False),
    sa.Column('availability_pre', sa.Enum('Oui', 'Non', 'Partielle', name='ambassador_availability_pre'), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='ambassador_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambassadors_status'), 'ambassadors', ['status'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.Enum('Tech/ESN', 'Fintech', 'Télécoms', 'Banque', 'ONG', 'Université', 'Médias', 'Autre', name='partner_sector'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_position', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('has_budget', sa.Enum('Oui — budget précis', 'Oui — à discuter', 'Non — exploration', name='partner_has_budget'), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=False),
    sa.Column('previous_sponsor', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('heard_from', sa.String(length=100), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'contacted', 'negotiating', 'confirmed', 'rejected', name='partner_status'), server_default='pending', nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['partner_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_level_id'), 'partners', ['level_id'], unique=False)
    op.create_index(op.f('ix_partners_status'), 'partners', ['status'], unique=False)
    op.create_foreign_key('fk_sessions_speaker_id', 'sessions', 'speakers', ['speaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # drop_table alone handles FK-backed indexes (MySQL forbids dropping an
    # index that still backs a foreign key) -- FK on sessions first, then
    # tables in dependency order.
    op.drop_constraint('fk_sessions_speaker_id', 'sessions', type_='foreignkey')
    op.drop_table('partners')
    op.drop_table('ambassadors')
    op.drop_table('speakers')
    op.drop_table('exhibitors')
