"""campaign_windows

Revision ID: 2c2d07493eb5
Revises: a9e9ba5fc6f7
Create Date: 2026-08-25 22:52:49.835369

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c2d07493eb5'
down_revision: str | Sequence[str] | None = 'a9e9ba5fc6f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum('call_for_speaker', 'ticketing', 'call_for_partner', 'call_for_ambassador', 'call_for_exhibitor', name='campaign_window_key'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_campaign_window_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    # Seed : dates par défaut, placeholders à ajuster par le back-office
    # (PATCH /api/admin/campaign-windows/:key, Phase 6.4) -- ordre des
    # étapes selon syncaconf/Infos.md, conférence le 18-20 août 2027.
    campaign_windows_table = sa.table(
        'campaign_windows',
        sa.column('key', sa.String),
        sa.column('start_at', sa.DateTime),
        sa.column('end_at', sa.DateTime),
    )
    op.bulk_insert(
        campaign_windows_table,
        [
            {
                'key': 'call_for_speaker',
                'start_at': '2026-10-01 00:00:00',
                'end_at': '2026-12-15 23:59:59',
            },
            {
                'key': 'call_for_partner',
                'start_at': '2026-10-01 00:00:00',
                'end_at': '2027-03-01 23:59:59',
            },
            {
                'key': 'ticketing',
                'start_at': '2027-01-15 00:00:00',
                'end_at': '2027-08-10 23:59:59',
            },
            {
                'key': 'call_for_ambassador',
                'start_at': '2027-01-01 00:00:00',
                'end_at': '2027-04-01 23:59:59',
            },
            {
                'key': 'call_for_exhibitor',
                'start_at': '2027-01-01 00:00:00',
                'end_at': '2027-06-01 23:59:59',
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_windows')
    # ### end Alembic commands ###
