"""rbac (roles, permissions, role_permissions, admin_users)

Revision ID: a9e9ba5fc6f7
Revises: 3f306df50f16
Create Date: 2026-08-25 22:47:14.051141

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9e9ba5fc6f7'
down_revision: str | Sequence[str] | None = '3f306df50f16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admin_users_role_id'), 'admin_users', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    # ### end Alembic commands ###

    # Seed: les 4 rôles + les permissions de base (planning_fastapi.md §2).
    # Détail RBAC (quel rôle a quelle permission) affiné en Phase 2 ; pour
    # l'instant superadmin a tout, les autres rôles n'ont que la lecture.
    roles_table = sa.table('roles', sa.column('id', sa.Integer), sa.column('name', sa.String))
    permissions_table = sa.table(
        'permissions', sa.column('id', sa.Integer), sa.column('code', sa.String)
    )
    role_permissions_table = sa.table(
        'role_permissions',
        sa.column('role_id', sa.Integer),
        sa.column('permission_id', sa.Integer),
    )

    role_names = ['superadmin', 'admin', 'editor', 'support']
    op.bulk_insert(roles_table, [{'name': name} for name in role_names])

    permission_codes = [
        'speakers.approve',
        'ambassadors.approve',
        'partners.manage',
        'exhibitors.manage',
        'payments.view',
        'campaign_windows.manage',
        'export.data',
        'roles.manage',
    ]
    op.bulk_insert(permissions_table, [{'code': code} for code in permission_codes])

    connection = op.get_bind()
    superadmin_id = connection.execute(
        sa.select(roles_table.c.id).where(roles_table.c.name == 'superadmin')
    ).scalar_one()
    permission_ids = connection.execute(sa.select(permissions_table.c.id)).scalars().all()
    op.bulk_insert(
        role_permissions_table,
        [{'role_id': superadmin_id, 'permission_id': pid} for pid in permission_ids],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('role_permissions')
    op.drop_table('admin_users')
    op.drop_table('roles')
    op.drop_table('permissions')
